//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Errores", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        internal static string CodigoDeError {
            get {
                return ResourceManager.GetString("CodigoDeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación satisfactoria. Cliente dispondrá de 48 horas y 3 intentos a partir de ahora para descargar el producto..
        /// </summary>
        internal static string msgActivarCompra {
            get {
                return ResourceManager.GetString("msgActivarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Escritura de Base de Datos.
        /// </summary>
        internal static string msgDBError {
            get {
                return ResourceManager.GetString("msgDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Error al abrir .zip, puede que algunos archivos esten dañados, por favor revise el archivo e intetelo nuevamente..
        /// </summary>
        internal static string msgDescomprimirZip {
            get {
                return ResourceManager.GetString("msgDescomprimirZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación ha sido ejecutada exitosamente..
        /// </summary>
        internal static string msgError0 {
            get {
                return ResourceManager.GetString("msgError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno. Por favor consulte al administrador..
        /// </summary>
        internal static string msgError1 {
            get {
                return ResourceManager.GetString("msgError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un registro con estos datos..
        /// </summary>
        internal static string msgError10 {
            get {
                return ResourceManager.GetString("msgError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún usuario asociado a este rol..
        /// </summary>
        internal static string msgError16 {
            get {
                return ResourceManager.GetString("msgError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Item asociado a este artista..
        /// </summary>
        internal static string msgError20 {
            get {
                return ResourceManager.GetString("msgError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Contenido Propuesto asociado a este artista..
        /// </summary>
        internal static string msgError21 {
            get {
                return ResourceManager.GetString("msgError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Item asociado a esta categoría..
        /// </summary>
        internal static string msgError25 {
            get {
                return ResourceManager.GetString("msgError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe el login ó email. Intente con otro..
        /// </summary>
        internal static string msgError30 {
            get {
                return ResourceManager.GetString("msgError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Catalogo asociado a este tipo..
        /// </summary>
        internal static string msgError35 {
            get {
                return ResourceManager.GetString("msgError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Item asociado a este proveedor..
        /// </summary>
        internal static string msgError40 {
            get {
                return ResourceManager.GetString("msgError40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Contenido Propuesto asociado a este proveedor..
        /// </summary>
        internal static string msgError41 {
            get {
                return ResourceManager.GetString("msgError41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Item en el Catalogo asociado a esta tasación..
        /// </summary>
        internal static string msgError45 {
            get {
                return ResourceManager.GetString("msgError45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Item asociado en la clasificación..
        /// </summary>
        internal static string msgError50 {
            get {
                return ResourceManager.GetString("msgError50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Item destacado asociado a este catalogo..
        /// </summary>
        internal static string msgError51 {
            get {
                return ResourceManager.GetString("msgError51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algún Usuario asociado a este catalogo..
        /// </summary>
        internal static string msgError52 {
            get {
                return ResourceManager.GetString("msgError52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algúna Categoría destacada asociado a este catalogo..
        /// </summary>
        internal static string msgError53 {
            get {
                return ResourceManager.GetString("msgError53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar. Existe algúna Compra asociada a este catalogo..
        /// </summary>
        internal static string msgError54 {
            get {
                return ResourceManager.GetString("msgError54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK CONSTRAINT violation occurred..
        /// </summary>
        internal static string msgError547 {
            get {
                return ResourceManager.GetString("msgError547", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatos de archivos inválidos..
        /// </summary>
        internal static string msgError61 {
            get {
                return ResourceManager.GetString("msgError61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se Puede Eliminar, el Control debe estar inactivo.
        /// </summary>
        internal static string msgError70 {
            get {
                return ResourceManager.GetString("msgError70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se Puede Eliminar, el control posee hijos asociados a el..
        /// </summary>
        internal static string msgError71 {
            get {
                return ResourceManager.GetString("msgError71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron portales con esa especificación.
        /// </summary>
        internal static string msgError81 {
            get {
                return ResourceManager.GetString("msgError81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error. Contacte a su administrador..
        /// </summary>
        internal static string msgErrorGenerico {
            get {
                return ResourceManager.GetString("msgErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay datos que mostrar.
        /// </summary>
        internal static string msgNoHayDatos {
            get {
                return ResourceManager.GetString("msgNoHayDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Debe seleccionar el contenido..
        /// </summary>
        internal static string msgSeleccionarDatos {
            get {
                return ResourceManager.GetString("msgSeleccionarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Cargando el componente ACE.ZipForge..
        /// </summary>
        internal static string msgUpLoadCom {
            get {
                return ResourceManager.GetString("msgUpLoadCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Copiando las imagenes ya descomprimidas..
        /// </summary>
        internal static string msgUpLoadCopy {
            get {
                return ResourceManager.GetString("msgUpLoadCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error eliminando el directorio temporal..
        /// </summary>
        internal static string msgUpLoadDelDirectory {
            get {
                return ResourceManager.GetString("msgUpLoadDelDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Eliminando el Archivo.
        /// </summary>
        internal static string msgUploaddelFile {
            get {
                return ResourceManager.GetString("msgUploaddelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creando Directorio..
        /// </summary>
        internal static string msgUpLoadDirectory {
            get {
                return ResourceManager.GetString("msgUpLoadDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo vacio..
        /// </summary>
        internal static string msgUpLoadEmpty {
            get {
                return ResourceManager.GetString("msgUpLoadEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensión Invalida..
        /// </summary>
        internal static string msgUpLoadExt {
            get {
                return ResourceManager.GetString("msgUpLoadExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Descomprimiendo los Archivos..
        /// </summary>
        internal static string msgUpLoadExtract {
            get {
                return ResourceManager.GetString("msgUpLoadExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error subiendo los Archivos..
        /// </summary>
        internal static string msgUpLoadFailure {
            get {
                return ResourceManager.GetString("msgUpLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Actualizando el Nombre en la base de datos.
        /// </summary>
        internal static string msgUploadnombre {
            get {
                return ResourceManager.GetString("msgUploadnombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo no válido..
        /// </summary>
        internal static string msgUpLoadNoValido {
            get {
                return ResourceManager.GetString("msgUpLoadNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan Tamaños de Imágenes..
        /// </summary>
        internal static string msgUpLoadSize {
            get {
                return ResourceManager.GetString("msgUpLoadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor colocar una ruta para la carga del archivo..
        /// </summary>
        internal static string msgUploadXml {
            get {
                return ResourceManager.GetString("msgUploadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Actualizando el Status de los Banners.
        /// </summary>
        internal static string msgupstatus {
            get {
                return ResourceManager.GetString("msgupstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Error al guardar los datos, por favor comuniquese con el administrador del sistema..
        /// </summary>
        internal static string msgXmlError {
            get {
                return ResourceManager.GetString("msgXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: El Archivo XML NO cumple con las especificaciones Técnicas..
        /// </summary>
        internal static string msgXmlEspInvalida {
            get {
                return ResourceManager.GetString("msgXmlEspInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: No se encuentra el archivo XML, por favor revise el archivo .zip e intetelo nuevamente..
        /// </summary>
        internal static string msgXmlNoExiste {
            get {
                return ResourceManager.GetString("msgXmlNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Archivo Invalido. Formato solicitado {.zip, .rar}.
        /// </summary>
        internal static string msgXmlNoValido {
            get {
                return ResourceManager.GetString("msgXmlNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en VerificarArchivoPreviews.
        /// </summary>
        internal static string msgXmlPreviews {
            get {
                return ResourceManager.GetString("msgXmlPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: No se encontraron uno o más archivos de preview, por favor revise el archivo .zip e itentelo nuevamente..
        /// </summary>
        internal static string msgXmlPreviewsInavalidos {
            get {
                return ResourceManager.GetString("msgXmlPreviewsInavalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Validar el XML Schema.
        /// </summary>
        internal static string msgXMLSchema {
            get {
                return ResourceManager.GetString("msgXMLSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido..
        /// </summary>
        internal static string txtCampoRequerido {
            get {
                return ResourceManager.GetString("txtCampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El password y la confirmación no coinciden..
        /// </summary>
        internal static string txtConfirmacionClave {
            get {
                return ResourceManager.GetString("txtConfirmacionClave", resourceCulture);
            }
        }
    }
}
