//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NewResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string txtActualizar {
            get {
                return ResourceManager.GetString("txtActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory.
        /// </summary>
        internal static string txtAdvisory {
            get {
                return ResourceManager.GetString("txtAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string txtAgregar {
            get {
                return ResourceManager.GetString("txtAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string txtArtista {
            get {
                return ResourceManager.GetString("txtArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string txtChargeType {
            get {
                return ResourceManager.GetString("txtChargeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string txtContactName {
            get {
                return ResourceManager.GetString("txtContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string txtDescripcion {
            get {
                return ResourceManager.GetString("txtDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        internal static string txtExportarExcel {
            get {
                return ResourceManager.GetString("txtExportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Id.
        /// </summary>
        internal static string txtFileId {
            get {
                return ResourceManager.GetString("txtFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handset Id.
        /// </summary>
        internal static string txtHandsetId {
            get {
                return ResourceManager.GetString("txtHandsetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiom.
        /// </summary>
        internal static string txtIdioma {
            get {
                return ResourceManager.GetString("txtIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsrcGrid.
        /// </summary>
        internal static string txtIsrcGrid {
            get {
                return ResourceManager.GetString("txtIsrcGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string txtKeyword {
            get {
                return ResourceManager.GetString("txtKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizador.
        /// </summary>
        internal static string txtLocalizador {
            get {
                return ResourceManager.GetString("txtLocalizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string TxtModelDevices {
            get {
                return ResourceManager.GetString("TxtModelDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Comma separated free text values to enrich content categorisation purposes).
        /// </summary>
        internal static string txtMsgKeyword {
            get {
                return ResourceManager.GetString("txtMsgKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Name.
        /// </summary>
        internal static string txtNombreArtista {
            get {
                return ResourceManager.GetString("txtNombreArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name  (English).
        /// </summary>
        internal static string txtNombreCategoriaEn {
            get {
                return ResourceManager.GetString("txtNombreCategoriaEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name  (Portuguese).
        /// </summary>
        internal static string txtNombreCategoriaPo {
            get {
                return ResourceManager.GetString("txtNombreCategoriaPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name  (Spanish).
        /// </summary>
        internal static string txtNombreCategoriaSp {
            get {
                return ResourceManager.GetString("txtNombreCategoriaSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string txtNombreItem {
            get {
                return ResourceManager.GetString("txtNombreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name (English).
        /// </summary>
        internal static string txtNombreItemEn {
            get {
                return ResourceManager.GetString("txtNombreItemEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name (Portuguese).
        /// </summary>
        internal static string txtNombreItemPo {
            get {
                return ResourceManager.GetString("txtNombreItemPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataform Name.
        /// </summary>
        internal static string txtNombrePlataforma {
            get {
                return ResourceManager.GetString("txtNombrePlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        internal static string txtNombreProveedor {
            get {
                return ResourceManager.GetString("txtNombreProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string txtProveedor {
            get {
                return ResourceManager.GetString("txtProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettlementId.
        /// </summary>
        internal static string txtSetElemntId {
            get {
                return ResourceManager.GetString("txtSetElemntId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Item Provider.
        /// </summary>
        internal static string txtStrId {
            get {
                return ResourceManager.GetString("txtStrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string txtTelefono {
            get {
                return ResourceManager.GetString("txtTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name.
        /// </summary>
        internal static string txtTipoItem {
            get {
                return ResourceManager.GetString("txtTipoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC.
        /// </summary>
        internal static string txtUpc {
            get {
                return ResourceManager.GetString("txtUpc", resourceCulture);
            }
        }
    }
}
