//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones:&amp;nbsp;.
        /// </summary>
        internal static string txtAcciones {
            get {
                return ResourceManager.GetString("txtAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar compra.
        /// </summary>
        internal static string txtActivarCompra {
            get {
                return ResourceManager.GetString("txtActivarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string txtActualizar {
            get {
                return ResourceManager.GetString("txtActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string txtAgregar {
            get {
                return ResourceManager.GetString("txtAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a la lista negra.
        /// </summary>
        internal static string txtAgregarListaNegra {
            get {
                return ResourceManager.GetString("txtAgregarListaNegra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema administración de Contenido .
        /// </summary>
        internal static string txtAplicacion {
            get {
                return ResourceManager.GetString("txtAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar Contenido.
        /// </summary>
        internal static string txtAprobar {
            get {
                return ResourceManager.GetString("txtAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar/Desaprobar Contenido.
        /// </summary>
        internal static string txtAprobarDesaprobar {
            get {
                return ResourceManager.GetString("txtAprobarDesaprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name artist.
        /// </summary>
        internal static string txtArtistName {
            get {
                return ResourceManager.GetString("txtArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Categorías.
        /// </summary>
        internal static string txtAsociarBanner {
            get {
                return ResourceManager.GetString("txtAsociarBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar Banners.
        /// </summary>
        internal static string txtAsociarBanners {
            get {
                return ResourceManager.GetString("txtAsociarBanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Catalogo.
        /// </summary>
        internal static string txtAsociarCatalogo {
            get {
                return ResourceManager.GetString("txtAsociarCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar contenido.
        /// </summary>
        internal static string txtAsociarContenido {
            get {
                return ResourceManager.GetString("txtAsociarContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar Destacados.
        /// </summary>
        internal static string txtAsociarDestacado {
            get {
                return ResourceManager.GetString("txtAsociarDestacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar Categoria Destacadas.
        /// </summary>
        internal static string txtAsociarDestacadoCategoria {
            get {
                return ResourceManager.GetString("txtAsociarDestacadoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar Item Destacados.
        /// </summary>
        internal static string txtAsociarDestacadoItem {
            get {
                return ResourceManager.GetString("txtAsociarDestacadoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar a excel.
        /// </summary>
        internal static string txtAsociarImportar {
            get {
                return ResourceManager.GetString("txtAsociarImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajar.
        /// </summary>
        internal static string txtBajar {
            get {
                return ResourceManager.GetString("txtBajar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido .
        /// </summary>
        internal static string txtBienvenido {
            get {
                return ResourceManager.GetString("txtBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        internal static string txtCampoRequerido {
            get {
                return ResourceManager.GetString("txtCampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string txtCancelar {
            get {
                return ResourceManager.GetString("txtCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar detalle.
        /// </summary>
        internal static string txtCerrarDetalle {
            get {
                return ResourceManager.GetString("txtCerrarDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string txtConfiguracion {
            get {
                return ResourceManager.GetString("txtConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desaprobar Contenido.
        /// </summary>
        internal static string txtDesaprobar {
            get {
                return ResourceManager.GetString("txtDesaprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacados.
        /// </summary>
        internal static string txtDestacados {
            get {
                return ResourceManager.GetString("txtDestacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbol de Navegación.
        /// </summary>
        internal static string txtDiagrama {
            get {
                return ResourceManager.GetString("txtDiagrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string txtEditar {
            get {
                return ResourceManager.GetString("txtEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string txtEliminar {
            get {
                return ResourceManager.GetString("txtEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar reporte.
        /// </summary>
        internal static string txtGenerarReporte {
            get {
                return ResourceManager.GetString("txtGenerarReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string txtGuardar {
            get {
                return ResourceManager.GetString("txtGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes.
        /// </summary>
        internal static string txtImagen {
            get {
                return ResourceManager.GetString("txtImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de eliminar el registro?.
        /// </summary>
        internal static string txtMensajeEliminar {
            get {
                return ResourceManager.GetString("txtMensajeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        internal static string txtMensajes {
            get {
                return ResourceManager.GetString("txtMensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string txtModificar {
            get {
                return ResourceManager.GetString("txtModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Control de Artistas.
        /// </summary>
        internal static string txtModuloArista {
            get {
                return ResourceManager.GetString("txtModuloArista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reclamos.
        /// </summary>
        internal static string txtModuloATC {
            get {
                return ResourceManager.GetString("txtModuloATC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Banners.
        /// </summary>
        internal static string txtModuloBanner {
            get {
                return ResourceManager.GetString("txtModuloBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Banner Imagen.
        /// </summary>
        internal static string txtModuloBannerImagen {
            get {
                return ResourceManager.GetString("txtModuloBannerImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Wap.
        /// </summary>
        internal static string txtModuloBannerWap {
            get {
                return ResourceManager.GetString("txtModuloBannerWap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Banners Web.
        /// </summary>
        internal static string txtModuloBannerWeb {
            get {
                return ResourceManager.GetString("txtModuloBannerWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para la carga de Banners.
        /// </summary>
        internal static string txtModuloCargaBanners {
            get {
                return ResourceManager.GetString("txtModuloCargaBanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para la carga de Banner Web.
        /// </summary>
        internal static string txtModuloCargaBannerWeb {
            get {
                return ResourceManager.GetString("txtModuloCargaBannerWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para la Carga de Viñetas.
        /// </summary>
        internal static string txtModuloCargabullets {
            get {
                return ResourceManager.GetString("txtModuloCargabullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para la carga de Fondos de Imagen.
        /// </summary>
        internal static string txtModuloCargaFondo {
            get {
                return ResourceManager.GetString("txtModuloCargaFondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para la Carga de Imagen.
        /// </summary>
        internal static string txtModuloCargaImagen {
            get {
                return ResourceManager.GetString("txtModuloCargaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para la carga de Contenido - Integración de Terceros.
        /// </summary>
        internal static string txtModuloCargaXml {
            get {
                return ResourceManager.GetString("txtModuloCargaXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Catalogos.
        /// </summary>
        internal static string txtModuloCatalogo {
            get {
                return ResourceManager.GetString("txtModuloCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Categorías.
        /// </summary>
        internal static string txtModuloCategoria {
            get {
                return ResourceManager.GetString("txtModuloCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorización de Contenido.
        /// </summary>
        internal static string txtModuloCategorizacion {
            get {
                return ResourceManager.GetString("txtModuloCategorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control y configuración de portales.
        /// </summary>
        internal static string txtModuloConfiguracion {
            get {
                return ResourceManager.GetString("txtModuloConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control Contenido Propuesto.
        /// </summary>
        internal static string txtModuloContenidoPropuesto {
            get {
                return ResourceManager.GetString("txtModuloContenidoPropuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control Parental.
        /// </summary>
        internal static string txtModuloControlParental {
            get {
                return ResourceManager.GetString("txtModuloControlParental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM.
        /// </summary>
        internal static string txtModuloCrm {
            get {
                return ResourceManager.GetString("txtModuloCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Control de Descacado Web.
        /// </summary>
        internal static string txtModuloDestacadoWeb {
            get {
                return ResourceManager.GetString("txtModuloDestacadoWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Imagen del Banner.
        /// </summary>
        internal static string txtModuloImagenBanner {
            get {
                return ResourceManager.GetString("txtModuloImagenBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Imagen por Banners Web.
        /// </summary>
        internal static string txtModuloImagenBannerWeb {
            get {
                return ResourceManager.GetString("txtModuloImagenBannerWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control Items aprobados - publicados.
        /// </summary>
        internal static string txtModuloItem {
            get {
                return ResourceManager.GetString("txtModuloItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Medios.
        /// </summary>
        internal static string txtModuloMedio {
            get {
                return ResourceManager.GetString("txtModuloMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Operadoras.
        /// </summary>
        internal static string txtModuloOperadora {
            get {
                return ResourceManager.GetString("txtModuloOperadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Generación de Portales Temáticos: Destacados.
        /// </summary>
        internal static string txtModuloPortalDestacado {
            get {
                return ResourceManager.GetString("txtModuloPortalDestacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Generación de Mensajes de Sistema.
        /// </summary>
        internal static string txtModuloPortalMensaje {
            get {
                return ResourceManager.GetString("txtModuloPortalMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control y configuración de Tasaciones para portales wap .
        /// </summary>
        internal static string txtModuloPortalTasacion {
            get {
                return ResourceManager.GetString("txtModuloPortalTasacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo para el control de portales temáticos web.
        /// </summary>
        internal static string txtModuloPortalTematicoWeb {
            get {
                return ResourceManager.GetString("txtModuloPortalTematicoWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Control de Promociones.
        /// </summary>
        internal static string txtModuloPromocion {
            get {
                return ResourceManager.GetString("txtModuloPromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Proveedores.
        /// </summary>
        internal static string txtModuloProveedor {
            get {
                return ResourceManager.GetString("txtModuloProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control Pruebas Técnicas Items.
        /// </summary>
        internal static string txtModuloPruebaTecnica {
            get {
                return ResourceManager.GetString("txtModuloPruebaTecnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Reportes.
        /// </summary>
        internal static string txtModuloReportes {
            get {
                return ResourceManager.GetString("txtModuloReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo control de Roles .
        /// </summary>
        internal static string txtModuloRol {
            get {
                return ResourceManager.GetString("txtModuloRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo control Seguridad - Usuario.
        /// </summary>
        internal static string txtModuloSeguridad {
            get {
                return ResourceManager.GetString("txtModuloSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control de Tasaciones.
        /// </summary>
        internal static string txtModuloTasacion {
            get {
                return ResourceManager.GetString("txtModuloTasacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Consulta Modelos de Teléfonos.
        /// </summary>
        internal static string txtModuloTelefono {
            get {
                return ResourceManager.GetString("txtModuloTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo de Generación de Portales Temáticos: Temas.
        /// </summary>
        internal static string txtModuloTemas {
            get {
                return ResourceManager.GetString("txtModuloTemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Generación de Portales Temáticos.
        /// </summary>
        internal static string txtModuloTematico {
            get {
                return ResourceManager.GetString("txtModuloTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Control Tipos de Catálogos.
        /// </summary>
        internal static string txtModuloTipoCatalogo {
            get {
                return ResourceManager.GetString("txtModuloTipoCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo control de Usuarios.
        /// </summary>
        internal static string txtModuloUsuario {
            get {
                return ResourceManager.GetString("txtModuloUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Administración de Wap Decks.
        /// </summary>
        internal static string txtModuloWapDeck {
            get {
                return ResourceManager.GetString("txtModuloWapDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string txtNombre {
            get {
                return ResourceManager.GetString("txtNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar Categorías.
        /// </summary>
        internal static string txtOrdenarCategorias {
            get {
                return ResourceManager.GetString("txtOrdenarCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        internal static string txtPromociones {
            get {
                return ResourceManager.GetString("txtPromociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades.
        /// </summary>
        internal static string txtPropiedades {
            get {
                return ResourceManager.GetString("txtPropiedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;Propiedades de:&amp;nbsp;.
        /// </summary>
        internal static string txtPropiedadesControl {
            get {
                return ResourceManager.GetString("txtPropiedadesControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar / Despublicar.
        /// </summary>
        internal static string txtPublicar {
            get {
                return ResourceManager.GetString("txtPublicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescar.
        /// </summary>
        internal static string txtRefrescar {
            get {
                return ResourceManager.GetString("txtRefrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Wap.
        /// </summary>
        internal static string txtRenderWap {
            get {
                return ResourceManager.GetString("txtRenderWap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Porting.
        /// </summary>
        internal static string txtReportePorting {
            get {
                return ResourceManager.GetString("txtReportePorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir.
        /// </summary>
        internal static string txtSubir {
            get {
                return ResourceManager.GetString("txtSubir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugerir Despublicación.
        /// </summary>
        internal static string txtSugerirDespublicacion {
            get {
                return ResourceManager.GetString("txtSugerirDespublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasación.
        /// </summary>
        internal static string txtTasacion {
            get {
                return ResourceManager.GetString("txtTasacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas.
        /// </summary>
        internal static string txtTemas {
            get {
                return ResourceManager.GetString("txtTemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Artista: {0}.
        /// </summary>
        internal static string txtTituloArtista {
            get {
                return ResourceManager.GetString("txtTituloArtista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Catalogo: {0}.
        /// </summary>
        internal static string txtTituloCatalogo {
            get {
                return ResourceManager.GetString("txtTituloCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Categoría: {0}.
        /// </summary>
        internal static string txtTituloCategoria {
            get {
                return ResourceManager.GetString("txtTituloCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Item propuesto: {0}.
        /// </summary>
        internal static string txtTituloItemPropuesto {
            get {
                return ResourceManager.GetString("txtTituloItemPropuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Operadora: {0}.
        /// </summary>
        internal static string txtTituloOperadora {
            get {
                return ResourceManager.GetString("txtTituloOperadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Proveedor: {0}.
        /// </summary>
        internal static string txtTituloProveedor {
            get {
                return ResourceManager.GetString("txtTituloProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Modelo de Teléfono: {0}.
        /// </summary>
        internal static string txtTituloTelefono {
            get {
                return ResourceManager.GetString("txtTituloTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Tipo Catálogo: {0}.
        /// </summary>
        internal static string txtTituloTipoCatalogo {
            get {
                return ResourceManager.GetString("txtTituloTipoCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su Ultima conexión fué: .
        /// </summary>
        internal static string txtUltConexion {
            get {
                return ResourceManager.GetString("txtUltConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalle.
        /// </summary>
        internal static string txtVerDetalle {
            get {
                return ResourceManager.GetString("txtVerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere por favor....
        /// </summary>
        internal static string txtWait {
            get {
                return ResourceManager.GetString("txtWait", resourceCulture);
            }
        }
    }
}
