<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageChargeType.aspx.cs" Inherits="ContentAdmin.PageChargeType" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .MyImageButton
        {
            cursor: hand;
        }
        .EditFormHeader td
        {
            font-size: 14px;
            padding: 4px !important;
            color: #0066cc;
        }
    </style>
    <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server" />
</head>
<body>
    <form id="form1" runat="server">
    <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
    </telerik:RadAjaxManager>
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
        <Scripts>
        </Scripts>
    </telerik:RadScriptManager>
    <telerik:RadGrid ID="RadGrid1" GridLines="None" runat="server" AllowAutomaticDeletes="True"
        AllowSorting="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True"
        AllowMultiRowEdit="True" AllowPaging="True" DataSourceID="SqlDataSource1" OnItemUpdated="RadGrid1_ItemUpdated"
        AllowFilteringByColumn="True" OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted"
        OnDataBound="RadGrid1_DataBound" AutoGenerateDeleteColumn="True" 
        AutoGenerateEditColumn="True" CellSpacing="0">
        <PagerStyle Mode="NextPrevAndNumeric" />
        <MasterTableView Width="100%" CommandItemDisplay="TopAndBottom" DataKeyNames="chargeTypeId"
            DataSourceID="SqlDataSource1" HorizontalAlign="NotSet" EditMode="InPlace" 
            AutoGenerateColumns="False">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column"></RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column"></ExpandCollapseColumn>
            <Columns>
                <telerik:GridBoundColumn DataField="chargeTypeId" DataType="System.Int32" 
                    FilterControlAltText="Filter chargeTypeId column" HeaderText="chargeTypeId" 
                    ReadOnly="True" SortExpression="chargeTypeId" UniqueName="chargeTypeId">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="chargeTypeName" 
                    FilterControlAltText="Filter chargeTypeName column" HeaderText="chargeTypeName" 
                    SortExpression="chargeTypeName" UniqueName="chargeTypeName">
                </telerik:GridBoundColumn>
            </Columns>
            <EditFormSettings>
                <FormTableItemStyle Wrap="False"></FormTableItemStyle>
                <FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle>
                <FormMainTableStyle GridLines="None" CellSpacing="0" CellPadding="3" BackColor="White"
                    Width="100%" />
                <FormTableStyle CellSpacing="0" CellPadding="2" Height="110px" BackColor="White" />
                <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle>
                <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="Cancel edit">
                </EditColumn>
                <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle>
            </EditFormSettings>

<PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>
        </MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>
    </telerik:RadGrid>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        DeleteCommand="DELETE FROM [ChargeType] WHERE [chargeTypeId] = @chargeTypeId" 
        InsertCommand="INSERT INTO [ChargeType] ([chargeTypeName]) VALUES (@chargeTypeName)" 
        SelectCommand="SELECT [chargeTypeId], [chargeTypeName] FROM [ChargeType]" 
        UpdateCommand="UPDATE [ChargeType] SET [chargeTypeName] = @chargeTypeName WHERE [chargeTypeId] = @chargeTypeId">
        <DeleteParameters>
            <asp:Parameter Name="chargeTypeId" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="chargeTypeName" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="chargeTypeName" Type="String" />
            <asp:Parameter Name="chargeTypeId" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </form>
</body>
</html>
