<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ContentAdmin.PageItemHandset.aspx.cs"
    Inherits="PageItemHandset" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
    <style type="text/css">
        .MyImageButton
        {
            cursor: hand;
        }
        .EditFormHeader td
        {
            font-size: 14px;
            padding: 4px !important;
            color: #0066cc;
        }
    </style>
    <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server" />
</head>
<body>
    <form id="form1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
        <Scripts>
        </Scripts>
    </telerik:RadScriptManager>
    <div style="width:600px;margin:auto">
    <h1>Supported Handsets</h1>
    <telerik:RadGrid ID="RadGrid1" GridLines="None" runat="server" AllowAutomaticDeletes="True"
        AllowSorting="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" 
            AllowPaging="True" DataSourceID="HandsetItems" OnItemUpdated="RadGrid1_ItemUpdated"
        AllowFilteringByColumn="True" OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted"
        OnDataBound="RadGrid1_DataBound" AutoGenerateDeleteColumn="True" 
            AutoGenerateEditColumn="True" CellSpacing="0">
        <PagerStyle Mode="NextPrevAndNumeric" />
        <MasterTableView Width="100%" CommandItemDisplay="TopAndBottom" 
            DataKeyNames="itemId,handsetId,fileId" DataSourceID="HandsetItems"
            HorizontalAlign="NotSet" EditMode="EditForms" AutoGenerateColumns="False">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column"></RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column"></ExpandCollapseColumn>
            <Columns>
                <telerik:GridTemplateColumn HeaderText="Item" FilterControlAltText="Filter itemId column" 
                    UniqueName="itemId" DataField="itemId">
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="itemId"></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                         <%#DataBinder.Eval(Container.DataItem, "itemId")%>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridTemplateColumn HeaderText="Handset" ItemStyle-Width="440px" 
                    DataField="handsetId" FilterControlAltText="Filter handsetId column" 
                    UniqueName="handsetId">
                    <ItemTemplate>
                        <%#DataBinder.Eval(Container.DataItem, "handsetName")%>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <telerik:RadComboBox runat="server" ID="handsetId" DataTextField="handsetName"
                            DataValueField="handsetId" DataSourceID="HandsetNames" SelectedValue='<%#Bind("handsetId") %>'>
                        </telerik:RadComboBox>
                    </EditItemTemplate>
                    <ItemStyle Width="440px"></ItemStyle>
                </telerik:GridTemplateColumn>
                <telerik:GridTemplateColumn HeaderText="File" ItemStyle-Width="440px" 
                    DataField="fileId" FilterControlAltText="Filter fileId column" 
                    UniqueName="fileId">
                    <ItemTemplate>
                        <%#DataBinder.Eval(Container.DataItem, "fileName")%>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <telerik:RadComboBox runat="server" ID="fileId" DataTextField="fileName"
                            DataValueField="fileId" DataSourceID="FileNames" SelectedValue='<%#Bind("fileId") %>'>
                        </telerik:RadComboBox>
                    </EditItemTemplate>
                    <ItemStyle Width="440px"></ItemStyle>

                </telerik:GridTemplateColumn>





            </Columns>


            <EditFormSettings>
                <FormTableItemStyle Wrap="False"></FormTableItemStyle>
                <FormTableStyle CellPadding="2" CellSpacing="0" BackColor="White" Height="110px"></FormTableStyle>
                <FormMainTableStyle CellPadding="3" CellSpacing="0" BackColor="White" Width="100%"></FormMainTableStyle>
                <FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle>
                <FormMainTableStyle GridLines="None" CellSpacing="0" CellPadding="3" BackColor="White" Width="100%" />
                <FormTableStyle CellSpacing="0" CellPadding="2" Height="110px" BackColor="White" />
                <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle>
                <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="Cancel edit"></EditColumn>
                <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle>
            </EditFormSettings>

<PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>
        </MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>
    </telerik:RadGrid>
    </div>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <asp:SqlDataSource 
    SelectCommand="SELECT IH.itemId ,IH.handsetId , 
                          H.handsetName + '- ' + H.handsetStrId AS handsetName, 
                          IH.fileId, F.fileName
                   FROM ItemHandset as IH 
                   INNER JOIN Handset as H on IH.handsetId = H.handsetId 
                   INNER JOIN Files as F on F.fileId=IH.fileId
                   WHERE (IH.itemId = @ItemId)
                   ORDER BY handsetName"
        
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        ID="HandsetItems" runat="server" 
        
        DeleteCommand="delete ItemHandset where itemId = @itemId and handsetId = @handsetId and fileId = @fileId " 
        InsertCommand="insert ItemHandset (itemId ,handsetId , fileId) values( @itemId , @handsetId ,  @fileId ) " 
        UpdateCommand="update ItemHandset  set  itemId = @itemId ,handsetId = @handsetId ,fileId = @fileId 
                       where itemId = @itemId and handsetId = @handsetId and fileId = @fileId ">
        <DeleteParameters>
            <asp:Parameter Name="itemId" />
            <asp:Parameter Name="handsetId" />
            <asp:Parameter Name="fileId" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="itemId" />
            <asp:Parameter Name="handsetId" />
            <asp:Parameter Name="fileId" />
        </InsertParameters>
        <SelectParameters>
            <asp:QueryStringParameter DbType="Int32" Name="ItemId" 
                QueryStringField="ItemId" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="itemId" />
            <asp:Parameter Name="handsetId" />
            <asp:Parameter Name="fileId" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="HandsetNames" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        SelectCommand="SELECT handsetId, { fn CONCAT({ fn CONCAT(handsetName, ' - ') }, handsetStrId) } AS handsetName FROM Handset order by handsetName, handsetStrId">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="FileNames" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        SelectCommand="SELECT fileId, fileName FROM Files where itemId = @ItemId order by fileName">
        <SelectParameters>
            <asp:QueryStringParameter DbType="Int32" Name="ItemId" 
                QueryStringField="ItemId" />
        </SelectParameters>
    </asp:SqlDataSource>
    </form>
</body>
</html>
