<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PagePlaformaFormatos.aspx.cs" Inherits="ContentAdmin.PagePlaformaFormatos" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .MyImageButton
        {
            cursor: hand;
        }
        .EditFormHeader td
        {
            font-size: 14px;
            padding: 4px !important;
            color: #0066cc;
        }
    </style>
    <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server" />
</head>
<body>

    <form id="form1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
        <Scripts>
        </Scripts>
    </telerik:RadScriptManager>
    <div style="width:400px;margin:auto">
    <h1>Supported Formats</h1>
    <telerik:RadGrid ID="RadGrid1" GridLines="None" runat="server" 
        AllowAutomaticDeletes="True" AllowAutomaticInserts="True" 
        AllowAutomaticUpdates="True" DataSourceID="DataSource1" 
        OnItemUpdated="RadGrid1_ItemUpdated" OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted"
        OnDataBound="RadGrid1_DataBound" AutoGenerateDeleteColumn="True" 
        CellSpacing="0" AutoGenerateEditColumn="True">
        <PagerStyle Mode="NextPrevAndNumeric" />
        <MasterTableView Width="100%" CommandItemDisplay="TopAndBottom"
            DataSourceID="DataSource1" HorizontalAlign="NotSet" EditMode="InPlace" 
            AutoGenerateColumns="False" AllowFilteringByColumn="True" 
            AllowPaging="True" AllowSorting="True" DataKeyNames="platformId,classTypeId">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column"></RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column"></ExpandCollapseColumn>
            <Columns>
                <telerik:GridBoundColumn DataField="platformId" DataType="System.Int32" 
                    Display="False" FilterControlAltText="Filter platformId column" 
                    HeaderText="platformId" SortExpression="platformId" UniqueName="platformId">
                </telerik:GridBoundColumn>
                <telerik:GridDropDownColumn DataField="classTypeId" DataType="System.String" 
                    FilterControlAltText="Filter classTypeId column" HeaderText="ClassTypeId" 
                    UniqueName="classTypeId" DataSourceID="ClassTypes" 
                    ListTextField="classTypeName" ListValueField="classTypeId">
                </telerik:GridDropDownColumn>
            </Columns>
            <EditFormSettings>
                <FormTableItemStyle Wrap="False"></FormTableItemStyle>
                <FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle>
                <FormMainTableStyle GridLines="None" CellSpacing="0" CellPadding="3" BackColor="White"
                    Width="100%" />
                <FormTableStyle CellSpacing="0" CellPadding="2" Height="110px" BackColor="White" />
                <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle>
                <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="Cancel edit">
                </EditColumn>
                <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle>
            </EditFormSettings>

<PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>
        </MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>
    </telerik:RadGrid>
    </div>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <asp:SqlDataSource DeleteCommand="DELETE PlatformFormats WHERE platformId =@platformId AND classTypeId = @classTypeId"
        InsertCommand="INSERT PlatformFormats (platformId, classTypeId) VALUES (@platformId, @classTypeId)"
        
        SelectCommand="SELECT platformId, classTypeId FROM PlatformFormats WHERE platformId = @platformId" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        ID="DataSource1" runat="server">
        <DeleteParameters>
            <asp:QueryStringParameter DbType="String" Name="platformId" QueryStringField="platformId"/>
            <asp:Parameter Name="classTypeId" />
        </DeleteParameters>
        <InsertParameters>
            <asp:QueryStringParameter DbType="Int32" Name="platformId" QueryStringField="platformId"/>
            <asp:Parameter Name="classTypeId" />
        </InsertParameters>
        <SelectParameters>
            <asp:QueryStringParameter DbType="Int32" Name="platformId" QueryStringField="platformId" />
        </SelectParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="ClassTypes" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        SelectCommand="SELECT classTypeId as classTypeId, classTypeId as classTypeName FROM ClassType"></asp:SqlDataSource>
    </form>
</body>
</html>
