<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PageCharge.aspx.cs" Inherits="ContentAdmin.PageCharge" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .MyImageButton
        {
            cursor: hand;
        }
        .EditFormHeader td
        {
            font-size: 14px;
            padding: 4px !important;
            color: #0066cc;
        }
        #RadGrid1
        {
            margin-right:auto;
            margin-left:auto;
        }
    </style>
    <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server" />
</head>
<body>

    <a href="PageChargeType.aspx">Charge Type Maintanance</a>
    <form id="form1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
        <Scripts>
        </Scripts>
    </telerik:RadScriptManager>
    <telerik:RadGrid ID="RadGrid1" GridLines="None" runat="server" AllowAutomaticDeletes="True"
        AllowSorting="True" AllowAutomaticInserts="True" 
        AllowAutomaticUpdates="True" AllowPaging="True" DataSourceID="DataSource1" OnItemUpdated="RadGrid1_ItemUpdated"
        AllowFilteringByColumn="True" OnItemDeleted="RadGrid1_ItemDeleted" OnItemInserted="RadGrid1_ItemInserted"
        OnDataBound="RadGrid1_DataBound" CellSpacing="0" 
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" 
        Width="900px">
        <PagerStyle Mode="NextPrevAndNumeric" />
        <MasterTableView Width="100%" CommandItemDisplay="TopAndBottom" 
            DataKeyNames="chargeId" DataSourceID="DataSource1"
            HorizontalAlign="NotSet" EditMode="popup" AutoGenerateColumns="False">
<CommandItemSettings ExportToPdfText="Export to PDF" ShowExportToExcelButton="True"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column"></RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column"></ExpandCollapseColumn>
            <Columns>
                <telerik:GridBoundColumn DataField="chargeId" DataType="System.Int32" 
                    FilterControlAltText="Filter chargeId column" HeaderText="chargeId" 
                    ReadOnly="True" SortExpression="chargeId" UniqueName="chargeId" 
                    Display="False">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="chargeDetail" 
                    FilterControlAltText="Filter chargeDetail column" HeaderText="Detail" 
                    SortExpression="chargeDetail" UniqueName="chargeDetail">
                    <ItemStyle Font-Bold="False" />
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="chargeAmount" DataType="System.Decimal" 
                    FilterControlAltText="Filter chargeAmount column" HeaderText="Amount" 
                    SortExpression="chargeAmount" UniqueName="chargeAmount">
                    <ItemStyle Font-Bold="True" HorizontalAlign="Right" />
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="chargeCourrency" 
                    FilterControlAltText="Filter chargeCourrency column" 
                    HeaderText="Currency" SortExpression="chargeCourrency" 
                    UniqueName="chargeCourrency">
                </telerik:GridBoundColumn>
                <telerik:GridDropDownColumn 
                    DataField="platformId" DataSourceID="platformDS" 
                    FilterControlAltText="Filter platformId column" HeaderText="Platform" 
                    ListTextField="platformName" ListValueField="platformId" 
                    UniqueName="platformId">
                </telerik:GridDropDownColumn>
                <telerik:GridDropDownColumn 
                    DataField="chargeTypeId" DataSourceID="chargeTypeDS" 
                    FilterControlAltText="Filter chargeTypeId column" HeaderText="Type" 
                    ListTextField="chargeTypeName" ListValueField="chargeTypeId" 
                    UniqueName="chargeTypeId">
                </telerik:GridDropDownColumn>
                <telerik:GridDropDownColumn 
                    DataField="contentTypeId" DataSourceID="contentTypeDS" 
                    FilterControlAltText="Filter chargeTypeId column" HeaderText="Content" 
                    ListTextField="contentTypeName" ListValueField="contentTypeId" 
                    UniqueName="contentTypeId">
                </telerik:GridDropDownColumn>
            </Columns>
            <EditFormSettings>
                <FormTableItemStyle Wrap="False"></FormTableItemStyle>
                <FormCaptionStyle CssClass="EditFormHeader"></FormCaptionStyle>
                <FormMainTableStyle GridLines="None" CellSpacing="0" CellPadding="3" BackColor="White"
                    Width="100%" />
                <FormTableStyle CellSpacing="0" CellPadding="2" Height="110px" BackColor="White" />
                <FormTableAlternatingItemStyle Wrap="False"></FormTableAlternatingItemStyle>
                <EditColumn ButtonType="ImageButton" UniqueName="EditCommandColumn1" CancelText="Cancel edit">
                </EditColumn>
                <FormTableButtonRowStyle HorizontalAlign="Right" CssClass="EditFormButtonRow"></FormTableButtonRowStyle>
            </EditFormSettings>

<PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>
        </MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>
    </telerik:RadGrid>
    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
    </telerik:RadWindowManager>
    <asp:SqlDataSource DeleteCommand="DELETE FROM Charge WHERE chargeID = @chargeID" InsertCommand="INSERT INTO Charge (chargeDetail, chargeAmount, chargeCourrency,  platformId, chargeTypeId, contentTypeId ) VALUES (@chargeDetail, @chargeAmount, @chargeCourrency, @platformId, @chargeTypeId, @contentTypeId)"
        SelectCommand="SELECT Charge.* FROM Charge" UpdateCommand="UPDATE Charge SET chargeDetail = @chargeDetail, chargeAmount = @chargeAmount, chargeCourrency = @chargeCourrency, platformId = @platformId, chargeTypeId = @chargeTypeId, contentTypeId = @contentTypeId WHERE chargeID = @chargeID"
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>"
        ProviderName="System.Data.SqlClient" ID="DataSource1" runat="server">
        <UpdateParameters>
            <asp:Parameter Name="chargeDetail" Type="String" />
            <asp:Parameter Name="chargeAmount" Type="Decimal" />
            <asp:Parameter Name="chargeCourrency" Type="String" />
            <asp:Parameter Name="chargeSts" Type="Int16" />
            <asp:Parameter Name="platformId" Type="Int16" />
            <asp:Parameter Name="chargeTypeId" Type="Int16" />
            <asp:Parameter Name="settlementId" Type="String" />
            <asp:Parameter Name="date" Type="DateTime" />
            <asp:Parameter Name="chargeID" Type="Int16" />
        </UpdateParameters>        
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="platformDS" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        SelectCommand="SELECT [platformId], [platformName] FROM [Platform]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="chargeTypeDS" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        SelectCommand="SELECT [chargeTypeId], [chargeTypeName] FROM [ChargeType]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="contentTypeDS" runat="server" 
        ConnectionString="<%$ ConnectionStrings:DB_ContentProviderConnectionString %>" 
        SelectCommand="SELECT [contentTypeId], [contentTypeName] FROM [ContentType]">
    </asp:SqlDataSource>

    </form>
</body>
</html>
